version: '2'
services: 
  bot-api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment: 
      NODE_ENV: development
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/app/bot-api
      - /home/app/bot-api/node_modules
    depends_on: 
      - mongodb
  mongodb:
    image: mongo:4.0.4
    ports: 
      - 27017:27017